# Helix Editor v23.03

theme = 'tokyo_night'

[editor]
line-number = "relative"
bufferline = "always"
shell = ["nu"]
cursorline = true
true-color = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.statusline]
separator = "│"

# Normal Mode
[keys.normal]
space = { space = ["collapse_selection", "keep_primary_selection"], q = ":buffer-close" } # collapse
S-esc = ["normal_mode", ":format", ":write"]

J = "extend_line_down"
K = "extend_line_up"
V = "extend_line"
x = "extend_to_line_bounds"
"$" = "extend_to_line_end"
"^" = "extend_to_line_start"

w = "move_next_word_end"
e = "move_next_word_start"

H = ":buffer-previous"
L = ":buffer-next"

## Windows-like movement
C-h = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-left = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-l = ["move_next_word_start", "move_char_left", "move_char_right"]
C-right = ["move_next_word_start", "move_char_left", "move_char_right"]

# Insert Mode
[keys.insert]
# j = { k = "normal_mode" } # turned off because it doesn't print virtual char
C-backspace = "delete_word_backward"

## Windows-like movement
C-h = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-left = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-l = ["move_next_word_start", "move_char_left", "move_char_right"]
C-right = ["move_next_word_start", "move_char_left", "move_char_right"]

